/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.sddl.web;

import br.com.cawal.sddl.SDDLRuntimeModule;
import br.com.cawal.sddl.SDDLStandaloneSetup;
import br.com.cawal.sddl.ide.SDDLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SDDLWebSetup extends SDDLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SDDLRuntimeModule(), new SDDLIdeModule(), new SDDLWebModule()));
	}
	
}
