/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui.AbstractAnalysisActivityDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AnalysisActivityDSLUiModule extends AbstractAnalysisActivityDSLUiModule {
  public AnalysisActivityDSLUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
