/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.validation;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.validation.AbstractAnalysisActivityDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLValidator extends AbstractAnalysisActivityDSLValidator {
}
