/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAnalysisActivityDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://dcm.ffclrp.usp.br/lssb/metamodels/analysis-activity-description.ecore"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://dcm.ffclrp.usp.br/lssb/metamodels/string-list-manipulator.ecore"));
		return result;
	}
}
