/*
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.parser.antlr;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.parser.antlr.internal.InternalDSLSyntaxParser;
import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.services.DSLSyntaxGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DSLSyntaxParser extends AbstractAntlrParser {

	@Inject
	private DSLSyntaxGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDSLSyntaxParser createParser(XtextTokenStream stream) {
		return new InternalDSLSyntaxParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Deployment";
	}

	public DSLSyntaxGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLSyntaxGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
