/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.AnalysisActivityDSLRuntimeModule;
import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.AnalysisActivityDSLStandaloneSetup;
import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide.AnalysisActivityDSLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLIdeSetup extends AnalysisActivityDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    AnalysisActivityDSLRuntimeModule _analysisActivityDSLRuntimeModule = new AnalysisActivityDSLRuntimeModule();
    AnalysisActivityDSLIdeModule _analysisActivityDSLIdeModule = new AnalysisActivityDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_analysisActivityDSLRuntimeModule, _analysisActivityDSLIdeModule));
  }
}
