/*
 * generated by Xtext 2.17.1
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAnalysisActivityDSLScopeProvider extends DelegatingScopeProvider {
}
