/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide


/**
 * Use this class to register ide components.
 */
class AnalysisActivityDSLIdeModule extends AbstractAnalysisActivityDSLIdeModule {
}
