/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ActDLStandaloneSetup extends ActDLStandaloneSetupGenerated {

	public static void doSetup() {
		new ActDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
