/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.sddl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SDDLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSDDLWebModule extends DefaultWebModule {

}
