/**
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.validation;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.validation.AbstractDSLSyntaxValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DSLSyntaxValidator extends AbstractDSLSyntaxValidator {
}
