/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AnalysisActivityDSLStandaloneSetup extends AnalysisActivityDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new AnalysisActivityDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
