/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide.contentassist.antlr;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide.contentassist.antlr.internal.InternalAnalysisActivityDSLParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class AnalysisActivityDSLTokenSource extends AbstractIndentationTokenSource {

	public AnalysisActivityDSLTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalAnalysisActivityDSLParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Implement me
		throw new UnsupportedOperationException("Implement me");
	}

	@Override
	protected int getEndTokenType() {
		// TODO Implement me
		throw new UnsupportedOperationException("Implement me");
	}

	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
