/**
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.ui;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.ui.AbstractDSLSyntaxUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DSLSyntaxUiModule extends AbstractDSLSyntaxUiModule {
  public DSLSyntaxUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
