<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="analysisactivityexceptions" nsURI="http://dcm.ffclrp.usp.br/lssb/metamodels/activity-exceptions.ecore"
    nsPrefix="aae">
  <eClassifiers xsi:type="ecore:EDataType" name="ParameterUpdateException" instanceClassName="br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitymodel.exceptions.ParameterUpdateException"
      serializable="false"/>
</ecore:EPackage>
