# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: pwd
      - run: git submodule init
      - run: git submodule update
      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - activityrest-dependencies-{{ checksum "pom.xml" }}
#            # fallback to using the latest cache if no exact match is found
#            - activityrest-dependencies-
#      - run: mvn dependency:go-offline # gets the project dependencies
#      - save_cache:
#          paths:
#             - ~/.m2
#          key: activityrest-dependencies-{{ checksum "pom.xml" }}
      # run tests!
      - run:
           command: ./scripts/compile-all.sh
#      - run: mvn integration-test

  test_archetype:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - run: echo "Write archetype test logic Use artifact an successfully build service"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_archetype:
          requires:
            - build
