/*
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.ui;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.syntax.ui.internal.SyntaxActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSLSyntaxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SyntaxActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SyntaxActivator activator = SyntaxActivator.getInstance();
		return activator != null ? activator.getInjector(SyntaxActivator.BR_USP_FFCLRP_DCM_LSSB_ACTIVITYREST_DEPLOYMENTMODEL_DSLSYNTAX) : null;
	}

}
