/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AnalysisActivityDSLRuntimeModule extends AbstractAnalysisActivityDSLRuntimeModule {
}
