/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui.contentassist;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui.contentassist.AbstractAnalysisActivityDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLProposalProvider extends AbstractAnalysisActivityDSLProposalProvider {
}
