/*
 * generated by Xtext 2.17.1
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ui.internal.TextualdslActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnalysisActivityDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TextualdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TextualdslActivator activator = TextualdslActivator.getInstance();
		return activator != null ? activator.getInjector(TextualdslActivator.BR_USP_FFCLRP_DCM_LSSB_RESTAURANT_ANALYSISACTIVITYDESCRIPTION_TEXTUALDSL_ANALYSISACTIVITYDSL) : null;
	}

}
