/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.AnalysisActivityDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLStandaloneSetup extends AnalysisActivityDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new AnalysisActivityDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
