/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ActDLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractActDLWebModule extends DefaultWebModule {

}
