/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.parser.antlr.internal.InternalAnalysisActivityDSLParser;

public class AnalysisActivityDSLTokenSource extends AbstractIndentationTokenSource {

	public AnalysisActivityDSLTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalAnalysisActivityDSLParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalAnalysisActivityDSLParser.RULE_ENTITY_START;
	}

	@Override
	protected int getEndTokenType() {
		return InternalAnalysisActivityDSLParser.RULE_ENTITY_END;
	}

}
