/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.web;

import br.com.cawal.ActDLRuntimeModule;
import br.com.cawal.ActDLStandaloneSetup;
import br.com.cawal.ide.ActDLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class ActDLWebSetup extends ActDLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ActDLRuntimeModule(), new ActDLIdeModule(), new ActDLWebModule()));
	}
	
}
