/*
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DSLSyntaxStandaloneSetup extends DSLSyntaxStandaloneSetupGenerated {

	def static void doSetup() {
		new DSLSyntaxStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
