/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.sddl.tests

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.Deployment
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(SDDLInjectorProvider)
class SDDLParsingTest {
	@Inject
	ParseHelper<Deployment> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
            deployment { 
                of service "gene-chart-report-by-dataset" { api-version "1.1" }
                into container 'kode' {
                        base-url 'http://kode.ffcrp.usp.br:8081/david-chart-report-by-dataset'
                        description 'Nice description' 
                    }
            }
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
