/*
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.ide


/**
 * Use this class to register ide components.
 */
class DSLSyntaxIdeModule extends AbstractDSLSyntaxIdeModule {
}
