/*
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link DSLSyntaxWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractDSLSyntaxWebModule extends DefaultWebModule {

}
