/*
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class AnalysisActivityDSLWebModule extends AbstractAnalysisActivityDSLWebModule {
}
