/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.sddl.parser.antlr;

import br.com.cawal.sddl.parser.antlr.internal.InternalSDDLParser;
import br.com.cawal.sddl.services.SDDLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SDDLParser extends AbstractAntlrParser {

	@Inject
	private SDDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSDDLParser createParser(XtextTokenStream stream) {
		return new InternalSDDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Deployment";
	}

	public SDDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SDDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
