/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractActDLScopeProvider extends DelegatingScopeProvider {
}
