# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Activity-REST Framework
email: ricardo.cawal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A framework for facilitating the adaptation of command-line analysis tools
  as RESTful web services through model-based development support.
baseurl: "/activity-rest-framework" # the subpath of your site, e.g. /blog
url: "https://cawal.github.io" # the base hostname & protocol for your site
twitter_username: cawal
github_username:  cawal

# Build settings
markdown: kramdown
collections:
        rim:
                output: true
        aadl:
                output: true

