/*
 * generated by Xtext 2.25.0
 */
package br.com.cawal.ui.tests;

import br.com.cawal.actdl.ui.internal.ActdlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ActDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ActdlActivator.getInstance().getInjector("br.com.cawal.ActDL");
	}

}
