/**
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.web;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.web.AbstractDSLSyntaxWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class DSLSyntaxWebModule extends AbstractDSLSyntaxWebModule {
}
