/**
 * generated by Xtext 2.18.0
 */
package br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.web;

import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.DSLSyntaxRuntimeModule;
import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.DSLSyntaxStandaloneSetup;
import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.ide.DSLSyntaxIdeModule;
import br.usp.ffclrp.dcm.lssb.activityrest.deploymentmodel.web.DSLSyntaxWebModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class DSLSyntaxWebSetup extends DSLSyntaxStandaloneSetup {
  @Override
  public Injector createInjector() {
    DSLSyntaxRuntimeModule _dSLSyntaxRuntimeModule = new DSLSyntaxRuntimeModule();
    DSLSyntaxIdeModule _dSLSyntaxIdeModule = new DSLSyntaxIdeModule();
    DSLSyntaxWebModule _dSLSyntaxWebModule = new DSLSyntaxWebModule();
    return Guice.createInjector(Modules2.mixin(_dSLSyntaxRuntimeModule, _dSLSyntaxIdeModule, _dSLSyntaxWebModule));
  }
}
