<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tooldescription" nsURI="http://dcm.ffclrp.usp.br/lssb/metamodels/tooldescription/1.0/"
    nsPrefix="br.usp.ffclrp.dcm.lssb.tooldescription">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumMultiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumMultiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalysisTool" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes a tool capable of performing a number of operations."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The basename of the executable, e.g., 'blast', 'hmmer3'.&#xA;This is the name the tool is called if its executable is in the PATH."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perfoms" ordered="false"
        upperBound="-1" eType="#//Operation" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toolExitCodes" ordered="false"
        upperBound="-1" eType="#//ExitStatus" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="0 is default for SUCCESS and need not to be presented.&#xA;Any other that is not presented is ALWAYS treated as FAILURE.&#xA;This field can provide additionalMessages for a error."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents some processing the tool can perform."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="AllCommandLineArgumentsMustBeDeclaredInOperationScope"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="AllCommandLineArgumentsMustBeDeclaredInOperationScope" value="&#xA;&#x9;&#x9;&#x9;self.commandLineArguments.dataElement->forAll(e | &#xA;&#x9;&#x9;&#x9;&#x9;self.parameters->includes(e) &#xA;&#x9;&#x9;&#x9;&#x9;or self.inputFiles->includes(e)&#xA;&#x9;&#x9;&#x9;&#x9;or self.OutputFiles->includes(e)&#xA;&#x9;&#x9;&#x9;)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
        upperBound="-1" eType="#//Parameter" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputFiles" ordered="false"
        upperBound="-1" eType="#//FileDescriptor" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OutputFiles" ordered="false"
        upperBound="-1" eType="#//FileDescriptor" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandLineArguments" upperBound="-1"
        eType="#//CommandLineArgument">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultInputRedirect" eType="#//FileDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultOutputRedirect"
        eType="#//FileDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultErrorStreamRedirect"
        eType="#//FileDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationSpecificExitStatus"
        ordered="false" upperBound="-1" eType="#//ExitStatus" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="0 is default for SUCCESS and need not to be presented.&#xA;Any other that is not presented is ALWAYS treated as FAILURE.&#xA;This field can provide additionalMessages for a error."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExitStatus">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ExitStatusNonZero"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ExitStatusNonZero" value="&#xA;&#x9;&#x9;&#x9;not (self.code = 0)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataElement" abstract="true" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="abstract class Input;&#xA;abstract class Output;Represents any element that store data for the tool"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true" eSuperTypes="#//NamedElement #//DataElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines a named parameter of the tool.&#xA;A parameter consists of some information passed that the value is passed&#xA;literally to the tool.&#xA;This abstract class is intended to be extended by subclasses that define&#xA;parameter kinds (e.g., IntegerValuedParameter, StringValuedParameter...)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralParameter" eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericValuedParameter" abstract="true"
      eSuperTypes="#//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="validRanges" ordered="false"
        upperBound="-1" eType="#//NumericRange" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximunValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValuedParameter" eSuperTypes="#//NumericValuedParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealValuedParameter" eSuperTypes="#//NumericValuedParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringValuedParameter" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegexBoundedStringValuedParameter" eSuperTypes="#//StringValuedParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regex" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileDescriptor" eSuperTypes="#//NamedElement #//DataElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A File consists of some parameter that is passed by reference to the&#xA;tool (its file path)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passedBy" lowerBound="1"
        eType="#//FileDescriptorReferenceType" defaultValueLiteral="FILE_PATHS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FileDescriptorReferenceType" serializable="false">
    <eLiterals name="FILE_PATHS"/>
    <eLiterals name="DIRECTORY_PATH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandLineArgument">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="class InputFile extends File,Input;&#xA;class OutputFile extends File,Output;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataElement" lowerBound="1"
        eType="#//DataElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="argumentFormatters" ordered="false"
        upperBound="-1" eType="#//ArgumentFormatter">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArgumentFormatter" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes some way to format the arguments given a&#xA;list of strings (parameters values or files/directory paths).&#xA;&#xA;An formater must have a format( input: String[*]) : string[*]&#xA;operation that allow to concatenate formatters.&#xA;Each string after the last formatters must be considered a&#xA;different CLI parameter."/>
    </eAnnotations>
    <eOperations name="format" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Acts as a pipe, allowing to concatenate calls.&#xA;Each string in the end of the pipe shall be mapped&#xA;as a different argument in the exec call."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
      <eParameters name="input" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinArgumentFormatter" eSuperTypes="#//ArgumentFormatter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Formats a collection joining the element values using a delimiter string."/>
    </eAnnotations>
    <eOperations name="format" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Join all the strings in the input list using delimiter.&#xA;Produces a list with only one string."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
      <eParameters name="input" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrependArgumentFormatter" eSuperTypes="#//ArgumentFormatter">
    <eOperations name="format" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Prepend all the strings in the input list using prefix.&#xA;Produces a list with the same number of strings."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
      <eParameters name="input" ordered="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/OCL/Collection">
          <details key="nullFree" value="false"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
