/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.AbstractAnalysisActivityDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLRuntimeModule extends AbstractAnalysisActivityDSLRuntimeModule {
}
