/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.web;

import br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.web.AbstractAnalysisActivityDSLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLWebModule extends AbstractAnalysisActivityDSLWebModule {
}
